<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Docente;

class DocenteSeeder extends Seeder
{
    public function run(): void
    {
        $docentes = [
            'ADMÁRCIO RODRIGUES MACHADO',
            'ALTIMAR VIEIRA DO AMARAL',
            'ANDRÉ DOS SANTOS VIEIRA',
            'ANDRÉ LUIZ FORMIGONI',
            'ANDRÉ LUIZ RODRIGUES DE CAMARGO',
            'ANDRÉA LUISA MARTINS DOS SANTOS',
            'ANDRÉA PAVAN PERIN',
            'ANGELA CRISTINA SANTOS VILCARROMERO',
            'ANTONIO CARLOS GOMES DE ALMEIDA',
            'ARNALDO GONÇALVES',
            'CARLOS ALEXANDRE SOARES',
            'CESARIO DE MORAES LEONEL FERREIRA',
            'CLAUDIO SERGIO SARTORI',
            'DAIANE RONCATO CARDOZO MONTEIRO',
            'DANIEL SOARES DE MARQUES',
            'DAVID NUNES ZANETI DE SOUZA',
            'DAVISON CARDOSO PINHEIRO',
            'DENIS APARECIDO NOGUEIRA DE DEUS',
            'DIEGO APARECIDO CARVALHO ALBUQUERQUE',
            'DIRLEI PAULINO PINTO',
            'DISCIPLINA NÃO OFERTADA 1° SEMESTRE DE 2',
            'DULCE HELENA SOARES VILLA NOVA',
            'EDSON FERREIRA PORTELA',
            'ELIANA PRESTES DE SOUZA',
            'ELVIO FRANCO DE CAMARGO ARANHA',
            'EM CONTRATAÇÃO',
            'EONÁ MORO RIBEIRO',
            'EVANDRO DONIZETTE BARROS DE CAMPOS',
            'FABIANA DE OLIVEIRA LINS KITEGROSKI',
            'FABIO AUGUSTO NOGUEIRA',
            'FABRIZIO DI SARNO',
            'FARID SALLUM NETO',
            'FELIPE ANTUNES DE OLIVEIRA RODRIGUES',
            'FELIPE AUGUSTO BUENO DE ALMEIDA',
            'FLAVIANO AGOSTINHO DE LIMA',
            'GABRIEL PRESTES AMÉRICO',
            'GIOVANNI FRANCESCO GUARNIERI',
            'HAROLD JOSÉ BORDINHÃO',
            'JARBAS TAVARES DOS SANTOS',
            'JAYME DE CAMPOS JÚNIOR',
            'JEFERSON NEDELCIU',
            'JOÃO CARLOS TEIXEIRA DOS SANTOS',
            'JOÃO FERNANDO DE MORAES SANCHES',
            'JOSÉ ANTONIO CAMPOS BADIN',
            'JOSÉ ANTONIO MICHELETTI',
            'JOSÉ CAMARGO MOREIRA',
            'JOSÉ CARLOS PIRES JUNIOR',
            'JOSÉ MARCIO MATHIAS',
            'JOSÉ MARIA NOVAES DOS SANTOS',
            'JOSÉ VICENTE DIAS MASCARENHAS',
            'JULIO CESAR DE LEMOS',
            'JULIO CESAR DOS SANTOS GONÇALVES',
            'LIS VIRGINIA RAMOS VIEIRA',
            'LOAMÍ DA SILVA SOUZA',
            'LUAN MARTINS DE ARAÚJO SILVA',
            'LUANA SOARES MUZILLE',
            'LUCAS CORREIA MENEGUETTE',
            'LUCIANA AKEMI NAKABAYASHI',
            'LUIS ANTONIO GALHEGO FERNANDES',
            'LUIS RICARDO OLIVEIRA SANTOS',
            'LUIZ ANTONIO VARGAS PINTO',
            'LUIZ PAULO CADIOLI',
            'MARCELO DA SILVA PROENÇA',
            'MARCELO DE CASTRO REBELLO',
            'MARCELO MENEZES',
            'MARCIO SILVA DE MACEDO',
            'MARCOS ANTONIO ROSA',
            'MARCOS TADEU MARCONDES NUNES',
            'MARIA ANGELINA BUENO PEREIRA LEITE',
            'MARIA APARECIDA DOS SANTOS',
            'MARIA DA PENHA SILVA GOMES',
            'MARIA DO CARMO VARA LOPES ORSI',
            'MARIA JOSÉ CARDOZO',
            'MAURÍCIO COZER DIAS',
            'MAURÍCIO DIOGO DA SILVA',
            'MAURÍCIO PEREZ',
            'MAYRA MARTINS GUANAES',
            'NADIA MARCUS',
            'NELSON GUERRA',
            'NEOENERGIA(ELEKTRO)',
            'NILTON JOSÉ PEREIRA',
            'OLAVO FELTER JÚNIOR',
            'ORLANDO HOMEN DE MELLO',
            'OSVALDO D ESTEFANO ROSICA',
            'OTÁVIO DOS SANTOS GAIJUTIS',
            'OTÁVIO LUIZ MEDEIROS TIBAGY',
            'PAULO CÉSAR JULIANO',
            'PAULO CÉSAR SIGNORI',
            'PAULO RUBENS ROCHA ALBINO',
            'PEDRO SÉRGIO ROSA',
            'RAFAEL DE SÁ MASCARENHAS',
            'RAFAEL DOS SANTOS LIMA',
            'RAPHAEL GARCIA MOARES DA FONSECA',
            'RAQUEL FERREIRA ROCHA',
            'RENATO CORRALES NOGUEIRA',
            'RESERVADO CRAS',
            'RICARDO COURA OLIVEIRA',
            'ROQUE VENTURA JUNIOR',
            'ROSANA BERTILA GIACOMAZZI',
            'ROSÂNGELA GONSALVES DE ARAÚJO',
            'SAMUEL ANTÔNIO VIEIRA',
            'SANDRA MAUREN ELL',
            'SANDRO GABRIEL LIBRETTI PRESTES',
            'SERGIO SOARES',
            'SIDINEI APARECIDO OLIVEIRA VIEIRA',
            'STEPHANIE CERQUEIRA SILVA',
            'TAIS DE OLIVEIRA SANTOS',
            'TANIA REGINA TONUS',
            'THAIS DE PAULA RIGOLETTO',
            'THIAGO RODRIGUES DE SOUZA PEREIRA',
            'VALÉRIA CRISTINA SCUDELER',
            'VALMIR EDUARDO GUIMARÃES CARDOSO',
            'VALMIR TADEU FERNANDES',
            'VANDERLEI GUILHERME DE MACEDO FILHO',
            'VIVIANE TAVARES DO AMARAL',
            'VOLNEY MATTOS DE OLIVEIRA',
            'WAGNER RODRIGUES FERREIRA',
            'WALTER MASSON',
        ];

        foreach ($docentes as $nome) {
            Docente::create([
                'nome' => $nome
            ]);
        }

        $this->command->info(count($docentes) . ' docentes criados com sucesso!');
    }
}